Music_Organizer/Models/Artist.cs
using System;
using System.Collections.Generic;

namespace Music_Organizer.Models
{
  public class Artist
  {
    public Artist()
    {
      this.JoinEntities = new HashSet<AlbumArtist>();
    }
    public int ArtistId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<AlbumArtist> JoinEntities { get;}
  }
}

Music_Organizer/Controllers/AlbumsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Music_Organizer.Models;
using System.Collections.Generic;
using System.Linq;

namespace Music_Organizer.Controllers
{
  public class AlbumsController : Controller
  {
    private readonly Music_OrganizerContext _db;

    public AlbumsController(Music_OrganizerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Album> model = _db.Albums.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MediumId = new SelectList(_db.Mediums, "MediumId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Album album, int MediumId)
    {
      _db.Albums.Add(album);
      _db.SaveChanges();
      if (MediumId != 0)
      {
        _db.MediumAlbum.Add(new MediumAlbum() { MediumId = MediumId, AlbumId = album.AlbumId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisAlbum = _db.Albums
        .Include(album => album.JoinEntities)
        .ThenInclude(join => join.Artist)
        .Include(album => album.JoinMediumAlbum)
        .ThenInclude(join => join.Medium)
        .FirstOrDefault(album => album.AlbumId == id);
      return View(thisAlbum);
    }
    
    public ActionResult Edit(int id)
    {
      var thisAlbum = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      ViewBag.MediumId = new SelectList(_db.Mediums, "MediumId", "Name");
      return View(thisAlbum);
    }

    [HttpPost]
    public ActionResult Edit(Album album, int MediumId)
    {
      if (MediumId != 0)
      {
        _db.MediumAlbum.Add(new MediumAlbum() { MediumId = MediumId, AlbumId = album.AlbumId});
        _db.SaveChanges();
      }
      _db.Entry(album).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisAlbum = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      return View(thisAlbum);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisAlbum = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      _db.Albums.Remove(thisAlbum);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMedium(int id)
    {
      var thisAlbum = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      ViewBag.MediumId = new SelectList(_db.Mediums, "MediumId", "Name");
      return View(thisAlbum);
    }

    [HttpPost]
    public ActionResult AddMedium(Album album, int MediumId)
    {
      if (MediumId != 0)
      {
        _db.MediumAlbum.Add(new MediumAlbum() { MediumId = MediumId, AlbumId = album.AlbumId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMedium(int joinId)
    {
        var joinEntry = _db.MediumAlbum.FirstOrDefault(entry => entry.MediumAlbumId == joinId);
        _db.MediumAlbum.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

Music_Organizer/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Music_Organizer.Models;
using System.Collections.Generic;
using System.Linq;

namespace Music_Organizer.Controllers
{
  public class ArtistsController : Controller
  {
    private readonly Music_OrganizerContext _db;

    public ArtistsController(Music_OrganizerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Artist> model = _db.Artists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      ViewBag.MediumId = new SelectList(_db.Mediums, "MediumId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Artist artist, int AlbumId, int MediumId)
    {
      _db.Artists.Add(artist);
      _db.SaveChanges();
      if (AlbumId != 0)
      {
        _db.AlbumArtist.Add(new AlbumArtist() { AlbumId = AlbumId, ArtistId = artist.ArtistId });
        _db.SaveChanges();
      }
      if (MediumId != 0)
      {
        _db.MediumArtist.Add(new MediumArtist() { MediumId = MediumId, ArtistId = artist.ArtistId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisArtist = _db.Artists
        .Include(Artist => Artist.JoinEntities)
        .ThenInclude(join => join.Album)
        .FirstOrDefault(Artist => Artist.ArtistId == id);
      return View(thisArtist);
    }

    public ActionResult Edit(int id)
    {
      Artist thisArtist = _db.Artists.FirstOrDefault(artist => artist.ArtistId == id);
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      ViewBag.MediumId = new SelectList(_db.Mediums, "MediumId", "Name");
      return View(thisArtist);
    }

    [HttpPost]
    public ActionResult Edit(Artist artist, int AlbumId)
    {
      if (AlbumId != 0)
      {
        _db.AlbumArtist.Add(new AlbumArtist() { AlbumId = AlbumId, ArtistId = artist.ArtistId });
      }
      _db.Entry(artist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisArtist = _db.Artists.FirstOrDefault(artist => artist.ArtistId == id);
      return View(thisArtist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisArtist = _db.Artists.FirstOrDefault(artist => artist.ArtistId == id);
      _db.Artists.Remove(thisArtist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAlbum(int id)
    {
      var thisArtist = _db.Artists.FirstOrDefault(artist => artist.ArtistId == id);
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      return View(thisArtist);
    }

    [HttpPost]
    public ActionResult AddAlbum(Artist artist, int AlbumId)
    {
      if (AlbumId != 0)
      {
        _db.AlbumArtist.Add(new AlbumArtist() { AlbumId = AlbumId, ArtistId = artist.ArtistId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteAlbum(int joinId)
    {
        var joinEntry = _db.AlbumArtist.FirstOrDefault(entry => entry.AlbumArtistId == joinId);
        _db.AlbumArtist.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult AddMedium(int id)
    {
      var thisArtist = _db.Artists.FirstOrDefault(artist => artist.ArtistId == id);
      ViewBag.MediumId = new SelectList(_db.Mediums, "MediumId", "Name");
      return View(thisArtist);
    }

    [HttpPost]
    public ActionResult AddMedium(Artist artist, int MediumId)
    {
      if (MediumId != 0)
      {
        _db.MediumArtist.Add(new MediumArtist() { MediumId = MediumId, ArtistId = artist.ArtistId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMedium(int joinId)
    {
        var joinEntry = _db.MediumArtist.FirstOrDefault(entry => entry.MediumArtistId == joinId);
        _db.MediumArtist.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

Music_Organizer/Views/Artists/AddAlbum.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Artist

<h2>Add an Album</h2>

<h4>Add an Album to this Artist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ArtistId)

    @Html.Label("Select Album")
    @Html.DropDownList("AlbumId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Music_Organizer/Views/Artists/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Artist

<h2>Add a Album</h2>

<h4>Add a Album to this Artist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ArtistId)

    @Html.Label("Select Album")
    @Html.DropDownList("AlbumId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Music_Organizer/Views/Artists/AddMedium.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Artist

<h2>Add an Medium</h2>

<h4>Add an Medium to this Artist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ArtistId)

    @Html.Label("Select Medium")
    @Html.DropDownList("MediumId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Music_Organizer/Views/Artists/Create.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Artist

<h4>Add a New Artist</h4>
<br>
<br>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Select Album")
  @Html.DropDownList("AlbumId")

  @Html.Label("Select Medium")
  @Html.DropDownList("MediumId")
 <br>
 <br>
  <input type="submit" value="Add New Artist"/>
}
<br>
<br>
<br>
<p>@Html.ActionLink("Show All Artists", "Index")</p>
<p>@Html.ActionLink("Show All Albums", "Index", "Albums")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Music_Organizer/Views/Artists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Artist

<h2>Are you sure you want to delete this Artist?</h2>
<br>
<br>
@using (Html.BeginForm())
{
  <p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
  <br>
  <br>
  <input type="submit" value="Delete" />
}
<br>
<br>
<br>
<p>@Html.ActionLink("Show All Artists", "Index")</p>
<p>@Html.ActionLink("Show All Albums", "Index", "Albums")</p>

Music_Organizer/Views/Artists/Details.cshtml
@{
  Layout = "_Layout";
}
@using Music_Organizer.Models 
@model Music_Organizer.Models.Artist

<h2>Artist Details</h2>
<br>
<br>
@using (Html.BeginForm()) 
{
  <p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
  <p>Albums:</p>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li><a href=/Albums/Details/@join.Album.AlbumId>@join.Album.Name</a></li>
  }
  </ul>
}
<br>
<br>
<br>
<p>@Html.ActionLink("Add a Album", "AddAlbum", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Add a Medium", "AddMedium", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Edit Artist", "Edit", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Delete Artist", "Delete", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Show All Artists", "Index")</p>
<p>@Html.ActionLink("Show All Albums", "Index", "Albums")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Music_Organizer/Views/Artists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Artist

<h2>Edit</h2>
<br>
<br>
<h4>Editing the Artist: @Html.DisplayFor(model => model.Name)</h4>
<br>
<br>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ArtistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Select Album")
  @Html.DropDownList("AlbumId")

  @Html.Label("Select Medium")
  @Html.DropDownList("MediumId")

  
  <br>
  <br>
  <input type="submit" value="Save" />
}
<br>
<br>
<br>
<p>@Html.ActionLink("Show All Artists", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Music_Organizer/Views/Artists/Index.cshtml
@{
  Layout = "_Layout";
}

@using Music_Organizer.Models;
@model List<Music_Organizer.Models.Artist>;

<h1>Artists</h1>
<br>
<br>
@if (@Model.Count == 0)
{
  <h3>No Artists have been added yet!</h3>
} 

@foreach (Artist artist in Model)
{
  <li>@Html.ActionLink($"{artist.Name}", "Details", new { id = artist.ArtistId })</li>
}
<br>
<br>
<br>
<p>@Html.ActionLink("Add New Artist", "Create")</p>
<p>@Html.ActionLink("Add New Album", "Create", "Albums")</p>
<p>@Html.ActionLink("Show All Albums", "Index", "Albums")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>