Music_Organizer/Models/Medium.cs
using System.Collections.Generic;

namespace Music_Organizer.Models
{
    public class Medium
    {
        public Medium()
        {
            this.JoinEntities = new HashSet<MediumArtist>();
            this.JoinMediumAlbum = new HashSet<MediumAlbum>();
        }

        public int MediumId { get; set; }
        public string Name { get; set; }
        public int AlbumId { get; set; }
        public virtual ICollection<MediumArtist> JoinEntities { get; set; }
        public virtual ICollection<MediumAlbum> JoinMediumAlbum { get; set; }
    }
}

Music_Organizer/Controllers/MediumsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Music_Organizer.Models;
using System.Collections.Generic;
using System.Linq;

namespace Music_Organizer.Controllers
{
  public class MediumsController : Controller
  {
    private readonly Music_OrganizerContext _db;

    public MediumsController(Music_OrganizerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Medium> model = _db.Mediums.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Medium medium)
    {
      _db.Mediums.Add(medium);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMedium = _db.Mediums
        .Include(Medium => Medium.JoinEntities)
        .ThenInclude(join => join.Artist)
        .Include(Medium => Medium.JoinMediumAlbum)
        .ThenInclude(join => join.Album)
        .FirstOrDefault(Medium => Medium.MediumId == id);
      return View(thisMedium);
    }
    
    public ActionResult Edit(int id)
    {
      var thisMedium = _db.Mediums.FirstOrDefault(medium => medium.MediumId == id);
      return View(thisMedium);
    }

    [HttpPost]
    public ActionResult Edit(Medium medium)
    {
      _db.Entry(medium).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMedium = _db.Mediums.FirstOrDefault(medium => medium.MediumId == id);
      return View(thisMedium);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMedium = _db.Mediums.FirstOrDefault(medium => medium.MediumId == id);
      _db.Mediums.Remove(thisMedium);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAlbum(int id)
    {
      var thisMedium = _db.Mediums.FirstOrDefault(medium => medium.MediumId == id);
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      return View(thisMedium);
    }

    [HttpPost]
    public ActionResult AddAlbum(Medium medium, int AlbumId)
    {
      if (AlbumId != 0)
      {
        _db.MediumAlbum.Add(new MediumAlbum() { AlbumId = AlbumId, MediumId = medium.MediumId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteAlbum(int joinId)
    {
        var joinEntry = _db.MediumAlbum.FirstOrDefault(entry => entry.MediumAlbumId == joinId);
        _db.MediumAlbum.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

Music_Organizer/Views/Mediums/AddAlbum.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Medium

<h2>Add an album</h2>

<h4>Add a album to this medium: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MediumId)

    @Html.Label("Select Album")
    @Html.DropDownList("AlbumId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Music_Organizer/Views/Mediums/AddArtist.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Medium

<h2>Add an Artist</h2>

<h4>Add an artist to this medium: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MediumId)

    @Html.Label("Select Artist")
    @Html.DropDownList("ArtistId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Music_Organizer/Views/Mediums/Create.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Medium

<h4>Add a new Medium</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new Medium" />
}
<p>@Html.ActionLink("Show all Mediums", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Music_Organizer/Views/Mediums/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Medium

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Music_Organizer/Views/Mediums/Details.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Medium;

<h2>Medium Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Medium does not contain any Artists</p>
}
else
{
  <h4>Artists the Medium contains:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li><a href=/Artists/Details/@join.Artist.ArtistId>@join.Artist.Name</a></li>
  }
  </ul>
}

@if(@Model.JoinMediumAlbum.Count == 0)
{
  <p>This Medium does not contain any Albums!</p>
}
else
{
  <h4>Albums the Medium contains:</h4>
  <ul>
  @foreach(var join in Model.JoinMediumAlbum)
  {
    <li><a href=/Albums/Details/@join.Album.AlbumId>@join.Album.Name</a></li>
  }
  </ul>
}
<p>@Html.ActionLink("Add a Album", "AddAlbum", "Mediums", new { id = Model.MediumId })</p>
<p>@Html.ActionLink("Add an Artist", "AddArtist", "Mediums", new { id = Model.MediumId })</p>
<p>@Html.ActionLink("Back to Mediums", "Index")</p>
<p>@Html.ActionLink("Edit Medium", "Edit", new { id = Model.MediumId })</p>
<p>@Html.ActionLink("Delete Medium", "Delete", new { id = Model.MediumId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Music_Organizer/Views/Mediums/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Music_Organizer.Models.Medium

<h2>Edit</h2>

<h4>Edit this Medium: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MediumId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Music_Organizer/Views/Mediums/Index.cshtml
@{
  Layout = "_Layout";
}

@using Music_Organizer.Models;

<h1>Mediums</h1>

@if (@Model.Count == 0)
{
  <h3>No Mediums have been added yet!</h3>
} 

<ul>
  @foreach(Medium medium in Model)
  {
    <li>@Html.ActionLink($"{medium.Name}", "Details", new { id = medium.MediumId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new Medium", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>